### ISSUE TITLE
BigQueryType.toTableRow does not serialize properly in lambda when there are custom types

### ISSUE THREAD

**Issue by hansencc** [nevillelyh/shapeless-datatype#16] opened 2018-03-26 14:23 UTC
This serializes, but `BigQuerySchema` does not know about the custom types. Note: `releases` is a `SCollection[Release]`.
```
      val bqType: BigQueryType[Release] = BigQueryType[Release]
      releases
        .map { a =>
          implicit val enumType
            : BaseBigQueryMappableType[MyEnum] =
            BigQueryType.at[MyEnum]("STRING")(
              a => MyEnum.fromName(a.toString).orNull,
              _.name)
          bqType.toTableRow(a)
        }
        .saveAsBigQuery(
          table,
          schema = BigQuerySchema[Release]
        )
```

This does not serialize:
```
      implicit val enumType
        : BaseBigQueryMappableType[MyEnum] =
        BigQueryType.at[MyEnum]("STRING")(
          a => MyEnum.fromName(a.toString).orNull,
          _.name)
      val bqType: BigQueryType[Release] = BigQueryType[Release]
      val schema = BigQuerySchema[Release]

      releases
        .map { a =>
          bqType.toTableRow(a)
        }
        .saveAsBigQuery(
          table,
          schema = schema
        )
```

```
Exception in thread "main" java.lang.IllegalArgumentException: unable to serialize anonymous function map ...
Caused by: java.io.NotSerializableException ...
```

**Comment by nevillelyh** [comment] 2018-03-26 17:28
`BaseBigQueryMappableType` extends `MappableType` which should be `Serializable`, as we as the other traits here:
https://github.com/nevillelyh/shapeless-datatype/blob/master/core/src/main/scala/shapeless/datatype/mappable/MappableType.scala

We should add a few tests too.

**Comment by nevillelyh** [comment] 2018-04-04 17:51
We can test serialization for `*Type` instances with the following snippet.
```scala
def ensureSerializable[A](a: A): Unit = {
    val baos = new ByteArrayOutputStream()
    val oos = new ObjectOutputStream(baos)
    oos.writeObject(a)
    oos.close()
    baos.close()
  }
```

**Comment by nevillelyh** [comment] 2018-04-04 17:55
Hmm... Looks like we already have a `SerializableUtils#ensureSerializable` method which is used in most tests. Somehow we missed this. Should just add a test case and fix impl.

**Comment by nevillelyh** [comment] 2018-04-05 14:38
Pushed a WIP branch. It's still failing for some edge cases.
https://github.com/nevillelyh/shapeless-datatype/tree/neville/serde-dbg

```
[info] ! BigQueryType.seqs: Exception raised on property evaluation.
[info] > ARG_0: Seqs([I@1311b9c2,List(),Vector())
[info] > Exception: java.io.NotSerializableException: scala.Array$$anon$2
[info] ! BigQueryType.repeated: Exception raised on property evaluation.
[info] > ARG_0: Repeated(List(),List(),List(),List(),List(),List(),List(),List(),List())
[info] > Exception: java.io.NotSerializableException: scala.collection.generic.GenTraversableFactory$$anon$1
[info] + BigQueryType.date time types: OK, passed 100 tests.
[info] + BigQueryType.required: OK, passed 100 tests.
[info] + BigQueryType.mixed: OK, passed 100 tests.
[info] + BigQueryType.custom: OK, passed 100 tests.
[info] + BigQueryType.optional: OK, passed 100 tests.
[info] + BigQueryType.nested: OK, passed 100 tests.
```

**Comment by nevillelyh** [comment] 2018-04-05 15:28
The `seqs` & `repeated` failures are caused by `CanBuildFrom` not serializable. I made a workaround and now it's hitting some implicit lookup issue.

**Comment by nevillelyh** [comment] 2018-04-09 17:26
So fixed almost everything except for `Array[T]`, since `Array.newBuilder` requires an `(implicit t: ClassTag[T])` argument which isn't available.

**Comment by nevillelyh** [comment] 2018-05-25 15:07
Fixed in https://github.com/nevillelyh/shapeless-datatype/commit/1445a267dda6b234c7c96718bf86c3090256cbd7 and https://github.com/nevillelyh/shapeless-datatype/commit/39b317badb42b37b3ced3e56d220479e329aa085

**Closed by nevillelyh** 2018-05-25 15:07 UTC
Labels: bug
